# SPDX-FileCopyrightText: 2025 Florian Müllner <fmuellner@gnome.org>
# SPDX-License-Identifier: GPL-2.0-or-later

include:
  - project: GNOME/citemplates
    file: flatpak/flatpak_ci_initiative.yml
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: 'flatpak'
  - project: Infrastructure/freedesktop-ci-templates
    file: templates/ci-fairy.yml

stages:
  - review
  - build
  - deploy

.skip-git-clone:
  variables:
    GIT_STRATEGY: none

.only-merge-requests:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^$/'
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      when: on_success

flatpak:
  extends: .flatpak
  stage: build
  variables:
    FLATPAK_MODULE: gnome-extensions-app
    MANIFEST_PATH: build-aux/flatpak/org.gnome.Extensions.json
    RUNTIME_REPO: https://sdk.gnome.org/gnome-nightly.flatpakrepo
    APP_ID: org.gnome.Extensions.Devel
    BUNDLE: org.gnome.Extensions.Devel.flatpak
  dependencies: []

nightly:
  extends: .publish_nightly
  dependencies:
    - flatpak

check-merge-request:
  extends:
    - .fdo.ci-fairy
    - .skip-git-clone
  stage: review
  variables:
    REPORT: check-merge-request-report.xml
  script:
    - ci-fairy check-merge-request --require-allow-collaboration --junit-xml=$REPORT
  artifacts:
    expire_in: 1 week
    reports:
      junit: $REPORT
  rules:
    - !reference [.only-merge-requests, rules]

check-commit-log:
  extends:
    - .fdo.ci-fairy
  stage: review
  variables:
    REPORT: commit-messages-report.xml
  script:
    - ci-fairy check-commits --junit-xml=$REPORT
  artifacts:
    expire_in: 1 week
    reports:
      junit: $REPORT
  rules:
    - !reference [.only-merge-requests, rules]

eslint:
  stage: review
  image:
    name: quay.io/fedora/nodejs-22
  script:
    - tools/run-eslint.sh

check-reuse:
  stage: review
  image:
    name: fsfe/reuse:latest
    entrypoint: ['']
  script:
    - reuse lint
